name: Go add React and Build binary

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # copy react-build from other repo into /infrastructure folder:
  clone:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy react-builds from other repo
        uses: rodrigorodriguescosta/checkout@main
        continue-on-error: true
        with:
          repository: mbzcloud-test/test-react-app
          token: ${{ secrets.GH_PACKAGE_PAT }}
          ref: build-artf #${{ env.BRANCH_NAME }}
          path: folder1

      - name: Display structure of downloaded files
        run: ls -R

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          #name: build
          path: folder1
          retention-days: 5

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        id: download
        # with:
        #   #name: build
        #   path: src

      - name: "Echo download path"
        run: echo ${{steps.download.outputs.download-path}}

      - name: Deploy to other repo
        uses: manzoorwanijk/action-deploy-to-repo@master
        with:
          src_dir: folder1
          target_owner: mbzcloud-test
          target_repo: go-backend
          target_dir: .
          target_branch: main
          # Optional
          access_token: ${{ secrets.GH_PACKAGE_PAT }}
          cleanup_command: "rm -rf infrastructure/"

  #build go with added react-build:
  build:
    runs-on: ubuntu-latest
    needs: clone

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      # build the artifact
      - name: Build
        run: go build -v ./...

      # - name: "Upload Artifact"
      #   uses: actions/upload-artifact@v3
      #   with:
      #     #name: build
      #     path: build

      # upload artifact
      - name: Upload build artifacts 📤
        uses: actions/upload-artifact@v3
        with:
          name: bmanager # name of zip on deploy
          path: hello # after-build directory to deploy
          if-no-files-found: error
          retention-days: 5

      - name: Download all workflow run artifacts 📥
        uses: actions/download-artifact@v3
        id: download
        # with:
        #   name: bmanager
        # #   path: src

      - name: "Echo download path"
        run: echo ${{steps.download.outputs.download-path}}

      # Store binary to other repo
      - name: Deploy to other repo
        uses: manzoorwanijk/action-deploy-to-repo@master
        with:
          src_dir: bmanager
          target_owner: mbzcloud-test
          target_repo: go-backend
          target_dir: go-binary
          target_branch: go-artf # default
          # Optional
          access_token: ${{ secrets.GH_PACKAGE_PAT }}
          cleanup_command: "rm -rf go-binary/*"
