name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      # - name: Upload build artifacts 📤
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: go-build # name of zip on deploy
      #     path: hello # after-build directory to deploy
      #     if-no-files-found: error

      # - name: Download artifact 📥
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: go-build
      #     path: .

      # - name: Display structure of downloaded files
      #   run: ls -R
#     - name: Test
#       run: go test -v ./...
